### ISSUE TITLE
index bug in chacha20 and salsa20

### ISSUE THREAD

**Issue by philanc** [philanc/plc#13]
Doing some tests with box, I found a silly bug that originates in my old chacha20 code and was imported in salsa20.  For all plain texts of length 64*n + 1, the last byte was ignored :-(. This is fixed. I added some test for that.

**Comment by catwell** [comment]
Nice catch. I guess we need more tests for everything.

I suppose you can close this issue now?

**Comment by philanc** [comment]
Sure. It was just FYI.
