### ISSUE TITLE
Add LuaRock package

### ISSUE THREAD

**Issue by imaia** [philanc/plc#14]
That would be quite helpful https://luarocks.org/

**Comment by catwell** [comment]
This basically means "make a stable release". There is none yet. In the meantime you can do:

    luarocks install https://raw.githubusercontent.com/philanc/plc/master/rockspec/plc-scm-1.rockspec

**Comment by philanc** [comment]
I am not sure I understand the relation between "a stable release" and the rockspec file (not familiar enough with Luarocks).

Should/can I just register the current rockspec (plc-scm-1.rockspec) at luarocks.org so that users can `luarocks install plc` and get the last version?

**Comment by catwell** [comment]
No, if you do that it will be classified as a development version and not install that way.

The easiest solution is to decide on a release number, add a tag and create a rockspec that installs that tag. See for instance [here](https://github.com/catwell/haricot/blob/master/rockspec/haricot-1.2-1.rockspec), in particular the "branch" field in "source", as opposed to the SCM rockspec [here](https://github.com/catwell/haricot/blob/master/rockspec/haricot-scm-1.rockspec). Then you can just register `luarocks upload` that rockspec.

**Comment by philanc** [comment]
Thanks for the explanation and for the example. I created a 'v0.5' release, added a rockspec for it and uploaded it to Luarocks.org.  

So now, it is possible to install plc (this release) with `luarock install plc`

Which is what I think Italo Maia suggested in the first post.

**Comment by catwell** [comment]
Yes, that's great, I just wasn't sure if you wanted to do it yet!

**Comment by philanc** [comment]
Thanks to Italo for the nudge and to you for the help!

**Comment by imaia** [comment]
Thanks @philanc @catwell
