### ISSUE TITLE
PBKDF2 and HMAC

### ISSUE THREAD

**Issue by RussellHaley** [philanc/plc#16]
Hi, 

I've been pilfering your library for some time now for MD5 and base64 functions. I'm attempting to re-create (in Lua) some javascript code that uses the node.js crypto library:

#Javascript
``` javascript
const crypto = require('crypto');

function print(str){
	console.log(str);
}

function createUserKey(user){
  if (user.password && user.password.length > 6) {
    user.salt = crypto.randomBytes(32).toString('base64');
    user.hash = hashPassword(user.password, user.salt);
  }
  else {
	  print("No password provided");
  }
  return user;
}

/**
 * Create instance method for hashing a password
 */
function hashPassword (password, salt) {
  if (salt && password) {
    return crypto.pbkdf2Sync(password, salt, 10000, 512, 'sha512').toString('base64');
  }
  else
  {
	  print("salt or pwd missing");
  }
};

var user = {username:'russell', password:'Testing123'};

print(JSON.stringify(createUserKey(user)));

```

These JavaScript functions were also pilfered from a work project which brings to light my problem: I have no idea what I'm doing!

I didn't see anything in your library called pbkdf2 so I went looking and found something in moteus' bgcrypto project: 
https://github.com/moteus/lua-bgcrypto-sha/blob/master/src/lua/pbkdf2.lua

but it seems to use his C libraries that have a different API than what you provide. I could *try* to pull in his pbkdf2 and hmac functions, but thought I would ask here first before I waste a bunch of time. As previously stated, I don't have much understanding of cryptography libraries. 

Do you have any thoughts on how I should proceed? I was hoping to use your libraries and stay with pure lua for portability. Otherwise I will look at using moteus' libraries or luaossl for openssl bindings. 

Thanks!
Russ

**Comment by philanc** [comment]
Hi Russ,

PBKDF2 has already been suggested. See issue #15 and my comment here https://github.com/philanc/plc/issues/15#issuecomment-441830353

As you can see from this issue thread, I am not too motivated to include PBKDF2 in my plc library :-)

In addition, the standard PBKFD2 function relies on HMAC-SHA1 which itself is based on SHA1 which is not implemented in plc.

If I implement SHA1 some day, I may add a HMAC-SHA1 function and maybe PBKFD2, but unfortunately for your use case, it's not here today.

(I don't know the node.js crypto lib, but from your code snippet I understand that they propose a PBKDF2 variant that may use alternate hash functions - here, SHA512? I don't think that it is standard, and rather than using PBKDF2 with an improved hash function, I would use a modern derivation function like scrypt or argon2i. but again, not a good fit for Pure Lua crypto...)

**Comment by philanc** [comment]
Actually, if you just need a good derivation function, not specifically the obsolete PBKDF2, and if you are ready to add a C library, you may be interested in my luazen library: https://github.com/philanc/luazen

It includes Argon2i which is arguably one of the best derivation function today (see https://en.wikipedia.org/wiki/Argon2). It is based on the Blake2b hash function.

luazen has **no dependencies**. All the crypto code is included. It builds by default with several crypto and compression functions you probably don't need, but you can easily build it with only the functions that you need:  Look at the Makefile, the list of included functions is in the variable 'FUNCS'. Just replace in the Makefile the default value with 
```   
FUNCS=-DBLAKE 
```
and you will get a quite small library (in that case, luazen.so on linux is ~ 18.5 KBytes) which includes the argon2i() Lua function. (You also get a randombytes() function as a bonus - I see you use one in your JS code snippet).

By the way, if you also need MD5 and Base64 functions, you can just add them to the Makefile FUNCS variable to get a slightly larger library (luazen.so ~ 22.6 KBytes)
```
FUNCS=-DBLAKE -DMD5 -DBASE64
```

Hope this helps!

**Comment by RussellHaley** [comment]
That's very helpful, thank you. Your answer is actually what I needed to know, but I'm trying to reproduce the API I've been given so I think I'm going to pull in bgcrypto (which seems to have what I need). I'll look to luazen when I'm working on my own things. I wonder where I could use it to deploy Minecraft servers? hmmm... 
Thanks!
Russ

**Comment by ingeniero-david** [comment]
Hi Philanc, can you please help with a pure lua function for Argon2i, i need it for an embedded system that doesn't allow to use c libraries. Thanks.

**Comment by philanc** [comment]
> Hi Philanc, can you please help with a pure lua function for Argon2i

I already have an implementation of Blake2b in plc, and Argon2 uses the permutation at the core of blake2b. The a complete implementation of Argon2 is significantly more complex than just iterating Blake2b computations.

So I'm afraid I don't have an implementation available, and don't plan to have one in the near future.

In addition, I am not sure that a pure Lua implementation would be usable, in terms of performance.  See my comment at https://github.com/philanc/plc/issues/15#issuecomment-441830353 - This applies to key derivation functions in general.
