### ISSUE TITLE
Merge with Lua-Lockbox

### ISSUE THREAD

**Issue by somesocks** [philanc/plc#2]
Hey philanc,

Someone pointed me to this repo recently, and I like what I see.  Good work!

I'm also the maintainer of a very similar lua crypto project (https://github.com/somesocks/lua-lockbox).  We've both built a suite of cryptographic primitives in pure Lua, and released them under the MIT license.

How would you feel about bringing your work into the Lockbox?  I'd be happy to add you as a contributor to the project.

**Comment by philanc** [comment]
Hi somesocks,

First, sorry for the late answer. I just seen your message today!! (never looked at the "Issues" tab until now... shame on me!)

I am fine with adding my "Pure Lua Crypto" functions to Lua-lockbox.  

But an issue may be that I wrote specifically for Lua 5.3, using extensively the bit operators (& | ^ << >>), the new 64-bit integers and the string pack/unpack functions.  And I noticed that lua-lockbox supports explicitly Lua 5.2

So my code may be difficult to use as-is. What do you think?

**Comment by philanc** [comment]
(looks like I closed this issue by mistake - am clearly not good with github :-))
