### ISSUE TITLE
Move tests to their own directory

### ISSUE THREAD

**Issue by RyanSquared** [philanc/plc#4]
Would make reading through the list of files *much* lighter on the eyes.

**Comment by philanc** [comment]
I see your point. And the more I had to the collection the worse it will be. 
On the other hand, I like having everything in the same directory. It makes it easy to run a test with a default LUA_PATH (including ./).  
Hmmm... Haven't set up my mind yet.

**Comment by RyanSquared** [comment]
Couldn't you just do `lua tests/<file>.lua` and have it work fine? This is what I do for my `spec/` folder for a project of mine (although, since I have it installed via `luarocks` as well, I need to run `luarocks make --local` beforehand).

**Comment by philanc** [comment]
Done. -- after a long rumination! :-)
